### PR TITLE
Create sendpulse.ino

### PR DESCRIPTION
**Pull request by petermbell**
An initial Arduino sketch that Utilizes a function "sendpulses" to send pulse (clock) , number of pulses, direction and an "enable" flag to a stepper motor H-Bridge controller.

### CODE REVIEW

**Comment by tristil** [comment]
Looks good. Would you add some notes in the README.md about what kind of hardware to look for? Like can I just buy something like this? http://www.radioshack.com/7-5vdc-micro-super-high-speed-motor/2730046.html#q=motor&didyoumean=1&start=2

**Comment by tristil** [comment]
If you make the changes and push them in a new commit they will show up here.

**Comment by petermbell** [comment]
Yes, I was thinking it would be good to have a list of hardware used. This
was mostly about being my first foray into using github. I'm still fairly
confused as to how to use it, but apparently managed to get this far.

On Fri, Mar 20, 2015 at 10:13 PM, Joseph Method notifications@github.com
wrote:

> If you make the changes and push them in a new commit they will show up
> here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkshirestech/telepresence-brain-arduino/pull/1#issuecomment-84218925
> .

## 

-- \* Peter Bell*

**Comment by tristil** [comment]
Okay, I'm going to merge this. Thanks! 

If you want a very thorough conceptual overview for Git (that's very command line focused though) there's this: http://git-scm.com/book/en/v2

But basically instead of creating a whole new PR you could have just added another commit in this branch and then pushed it.

**Pull request merged**
